version: '3'

services:
  wordpress:
    image: wordpress:latest # 最新版のWordPress公式イメージを利用
    ports:
      - "3000:80" # ポート番号の設定
    depends_on:
      - mysql # mysqlを立ち上げた後にWordpressを立ち上げる設定
    env_file: .env # 環境変数の定義に.envを利用
    volumes:
        - ./wp-content:/var/www/html/wp-content # マウントするディレクトリを指定

  mysql:
    image: mysql:5.7 # MySQL5.7公式イメージを利用
    env_file: .env # 環境変数の定義に.envを利用
    ports:
      - "3306:3306" #ポート番号の設定