version: '3'

services:
  wordpress:
    platform: linux/x86_64
    image: wordpress:latest
    ports:
      - '3000:80'
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  mysql:
    image: mysql:5.7
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:

networks:
  app-network:
